/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.fau.cs7.daceDS.datamodel;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CtrlMsg extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4186747663685844186L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CtrlMsg\",\"namespace\":\"eu.fau.cs7.daceDS.datamodel\",\"fields\":[{\"name\":\"Sender\",\"type\":\"string\"},{\"name\":\"Command\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CtrlMsg> ENCODER =
      new BinaryMessageEncoder<CtrlMsg>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CtrlMsg> DECODER =
      new BinaryMessageDecoder<CtrlMsg>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CtrlMsg> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CtrlMsg> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CtrlMsg> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CtrlMsg>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CtrlMsg to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CtrlMsg from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CtrlMsg instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CtrlMsg fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence Sender;
   private java.lang.CharSequence Command;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CtrlMsg() {}

  /**
   * All-args constructor.
   * @param Sender The new value for Sender
   * @param Command The new value for Command
   */
  public CtrlMsg(java.lang.CharSequence Sender, java.lang.CharSequence Command) {
    this.Sender = Sender;
    this.Command = Command;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Sender;
    case 1: return Command;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Sender = (java.lang.CharSequence)value$; break;
    case 1: Command = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Sender' field.
   * @return The value of the 'Sender' field.
   */
  public java.lang.CharSequence getSender() {
    return Sender;
  }


  /**
   * Sets the value of the 'Sender' field.
   * @param value the value to set.
   */
  public void setSender(java.lang.CharSequence value) {
    this.Sender = value;
  }

  /**
   * Gets the value of the 'Command' field.
   * @return The value of the 'Command' field.
   */
  public java.lang.CharSequence getCommand() {
    return Command;
  }


  /**
   * Sets the value of the 'Command' field.
   * @param value the value to set.
   */
  public void setCommand(java.lang.CharSequence value) {
    this.Command = value;
  }

  /**
   * Creates a new CtrlMsg RecordBuilder.
   * @return A new CtrlMsg RecordBuilder
   */
  public static eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder newBuilder() {
    return new eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder();
  }

  /**
   * Creates a new CtrlMsg RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CtrlMsg RecordBuilder
   */
  public static eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder newBuilder(eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder other) {
    if (other == null) {
      return new eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder();
    } else {
      return new eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder(other);
    }
  }

  /**
   * Creates a new CtrlMsg RecordBuilder by copying an existing CtrlMsg instance.
   * @param other The existing instance to copy.
   * @return A new CtrlMsg RecordBuilder
   */
  public static eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder newBuilder(eu.fau.cs7.daceDS.datamodel.CtrlMsg other) {
    if (other == null) {
      return new eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder();
    } else {
      return new eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder(other);
    }
  }

  /**
   * RecordBuilder for CtrlMsg instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CtrlMsg>
    implements org.apache.avro.data.RecordBuilder<CtrlMsg> {

    private java.lang.CharSequence Sender;
    private java.lang.CharSequence Command;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Sender)) {
        this.Sender = data().deepCopy(fields()[0].schema(), other.Sender);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Command)) {
        this.Command = data().deepCopy(fields()[1].schema(), other.Command);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CtrlMsg instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.fau.cs7.daceDS.datamodel.CtrlMsg other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.Sender)) {
        this.Sender = data().deepCopy(fields()[0].schema(), other.Sender);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Command)) {
        this.Command = data().deepCopy(fields()[1].schema(), other.Command);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Sender' field.
      * @return The value.
      */
    public java.lang.CharSequence getSender() {
      return Sender;
    }


    /**
      * Sets the value of the 'Sender' field.
      * @param value The value of 'Sender'.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder setSender(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Sender = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Sender' field has been set.
      * @return True if the 'Sender' field has been set, false otherwise.
      */
    public boolean hasSender() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Sender' field.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder clearSender() {
      Sender = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Command' field.
      * @return The value.
      */
    public java.lang.CharSequence getCommand() {
      return Command;
    }


    /**
      * Sets the value of the 'Command' field.
      * @param value The value of 'Command'.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder setCommand(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Command = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Command' field has been set.
      * @return True if the 'Command' field has been set, false otherwise.
      */
    public boolean hasCommand() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Command' field.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.CtrlMsg.Builder clearCommand() {
      Command = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CtrlMsg build() {
      try {
        CtrlMsg record = new CtrlMsg();
        record.Sender = fieldSetFlags()[0] ? this.Sender : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Command = fieldSetFlags()[1] ? this.Command : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CtrlMsg>
    WRITER$ = (org.apache.avro.io.DatumWriter<CtrlMsg>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CtrlMsg>
    READER$ = (org.apache.avro.io.DatumReader<CtrlMsg>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.Sender);

    out.writeString(this.Command);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Sender = in.readString(this.Sender instanceof Utf8 ? (Utf8)this.Sender : null);

      this.Command = in.readString(this.Command instanceof Utf8 ? (Utf8)this.Command : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Sender = in.readString(this.Sender instanceof Utf8 ? (Utf8)this.Sender : null);
          break;

        case 1:
          this.Command = in.readString(this.Command instanceof Utf8 ? (Utf8)this.Command : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










