/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.fau.cs7.daceDS.datamodel;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Meso extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4029503210061685942L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Meso\",\"namespace\":\"eu.fau.cs7.daceDS.datamodel\",\"fields\":[{\"name\":\"vehicleID\",\"type\":\"string\"},{\"name\":\"link\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"route\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Meso> ENCODER =
      new BinaryMessageEncoder<Meso>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Meso> DECODER =
      new BinaryMessageDecoder<Meso>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Meso> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Meso> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Meso> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Meso>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Meso to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Meso from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Meso instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Meso fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence vehicleID;
   private java.lang.CharSequence link;
   private java.lang.CharSequence type;
   private java.util.List<java.lang.CharSequence> route;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Meso() {}

  /**
   * All-args constructor.
   * @param vehicleID The new value for vehicleID
   * @param link The new value for link
   * @param type The new value for type
   * @param route The new value for route
   */
  public Meso(java.lang.CharSequence vehicleID, java.lang.CharSequence link, java.lang.CharSequence type, java.util.List<java.lang.CharSequence> route) {
    this.vehicleID = vehicleID;
    this.link = link;
    this.type = type;
    this.route = route;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return vehicleID;
    case 1: return link;
    case 2: return type;
    case 3: return route;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: vehicleID = (java.lang.CharSequence)value$; break;
    case 1: link = (java.lang.CharSequence)value$; break;
    case 2: type = (java.lang.CharSequence)value$; break;
    case 3: route = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'vehicleID' field.
   * @return The value of the 'vehicleID' field.
   */
  public java.lang.CharSequence getVehicleID() {
    return vehicleID;
  }


  /**
   * Sets the value of the 'vehicleID' field.
   * @param value the value to set.
   */
  public void setVehicleID(java.lang.CharSequence value) {
    this.vehicleID = value;
  }

  /**
   * Gets the value of the 'link' field.
   * @return The value of the 'link' field.
   */
  public java.lang.CharSequence getLink() {
    return link;
  }


  /**
   * Sets the value of the 'link' field.
   * @param value the value to set.
   */
  public void setLink(java.lang.CharSequence value) {
    this.link = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'route' field.
   * @return The value of the 'route' field.
   */
  public java.util.List<java.lang.CharSequence> getRoute() {
    return route;
  }


  /**
   * Sets the value of the 'route' field.
   * @param value the value to set.
   */
  public void setRoute(java.util.List<java.lang.CharSequence> value) {
    this.route = value;
  }

  /**
   * Creates a new Meso RecordBuilder.
   * @return A new Meso RecordBuilder
   */
  public static eu.fau.cs7.daceDS.datamodel.Meso.Builder newBuilder() {
    return new eu.fau.cs7.daceDS.datamodel.Meso.Builder();
  }

  /**
   * Creates a new Meso RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Meso RecordBuilder
   */
  public static eu.fau.cs7.daceDS.datamodel.Meso.Builder newBuilder(eu.fau.cs7.daceDS.datamodel.Meso.Builder other) {
    if (other == null) {
      return new eu.fau.cs7.daceDS.datamodel.Meso.Builder();
    } else {
      return new eu.fau.cs7.daceDS.datamodel.Meso.Builder(other);
    }
  }

  /**
   * Creates a new Meso RecordBuilder by copying an existing Meso instance.
   * @param other The existing instance to copy.
   * @return A new Meso RecordBuilder
   */
  public static eu.fau.cs7.daceDS.datamodel.Meso.Builder newBuilder(eu.fau.cs7.daceDS.datamodel.Meso other) {
    if (other == null) {
      return new eu.fau.cs7.daceDS.datamodel.Meso.Builder();
    } else {
      return new eu.fau.cs7.daceDS.datamodel.Meso.Builder(other);
    }
  }

  /**
   * RecordBuilder for Meso instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Meso>
    implements org.apache.avro.data.RecordBuilder<Meso> {

    private java.lang.CharSequence vehicleID;
    private java.lang.CharSequence link;
    private java.lang.CharSequence type;
    private java.util.List<java.lang.CharSequence> route;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.fau.cs7.daceDS.datamodel.Meso.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.vehicleID)) {
        this.vehicleID = data().deepCopy(fields()[0].schema(), other.vehicleID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.link)) {
        this.link = data().deepCopy(fields()[1].schema(), other.link);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.route)) {
        this.route = data().deepCopy(fields()[3].schema(), other.route);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Meso instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.fau.cs7.daceDS.datamodel.Meso other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.vehicleID)) {
        this.vehicleID = data().deepCopy(fields()[0].schema(), other.vehicleID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.link)) {
        this.link = data().deepCopy(fields()[1].schema(), other.link);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.route)) {
        this.route = data().deepCopy(fields()[3].schema(), other.route);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'vehicleID' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehicleID() {
      return vehicleID;
    }


    /**
      * Sets the value of the 'vehicleID' field.
      * @param value The value of 'vehicleID'.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder setVehicleID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.vehicleID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleID' field has been set.
      * @return True if the 'vehicleID' field has been set, false otherwise.
      */
    public boolean hasVehicleID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'vehicleID' field.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder clearVehicleID() {
      vehicleID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'link' field.
      * @return The value.
      */
    public java.lang.CharSequence getLink() {
      return link;
    }


    /**
      * Sets the value of the 'link' field.
      * @param value The value of 'link'.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder setLink(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.link = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'link' field has been set.
      * @return True if the 'link' field has been set, false otherwise.
      */
    public boolean hasLink() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'link' field.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder clearLink() {
      link = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder setType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder clearType() {
      type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'route' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getRoute() {
      return route;
    }


    /**
      * Sets the value of the 'route' field.
      * @param value The value of 'route'.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder setRoute(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.route = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'route' field has been set.
      * @return True if the 'route' field has been set, false otherwise.
      */
    public boolean hasRoute() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'route' field.
      * @return This builder.
      */
    public eu.fau.cs7.daceDS.datamodel.Meso.Builder clearRoute() {
      route = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Meso build() {
      try {
        Meso record = new Meso();
        record.vehicleID = fieldSetFlags()[0] ? this.vehicleID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.link = fieldSetFlags()[1] ? this.link : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.type = fieldSetFlags()[2] ? this.type : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.route = fieldSetFlags()[3] ? this.route : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Meso>
    WRITER$ = (org.apache.avro.io.DatumWriter<Meso>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Meso>
    READER$ = (org.apache.avro.io.DatumReader<Meso>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.vehicleID);

    out.writeString(this.link);

    out.writeString(this.type);

    long size0 = this.route.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.route) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.vehicleID = in.readString(this.vehicleID instanceof Utf8 ? (Utf8)this.vehicleID : null);

      this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.route;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("route").schema());
        this.route = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.vehicleID = in.readString(this.vehicleID instanceof Utf8 ? (Utf8)this.vehicleID : null);
          break;

        case 1:
          this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);
          break;

        case 2:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.route;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("route").schema());
            this.route = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










